server:
  port: 8888


spring:
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  aop:
    auto: true
  data:
    mongodb:
      host: localhost # mongodb的连接地址
      port: 27017 # mongodb的连接端口号
      database: work-log # mongodb的连接的数据库
  datasource:
    name: worklog #数据库名
    url: jdbc:mysql://43.139.5.93:3306/worklog?characterEncoding=utf8&useSSL=false
    username: worklog
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
    database: 0
    password:
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
    timeout: 3000ms
  mail:
    host: smtp.qq.com
    username: 2241375541@qq.com
    password: gajcijenjehuecgb
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    port: 587
    from: 2241375541@qq.com


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:com/**/mapper/*.xml

redis:
  key:
    verification:
      code: "code:"
      expireTime: 120 # 验证码超时时间

# MinIO对象存储相关配置
minio:
  endpoint: http://minio.origami.wang #MinIO服务所在地址
  bucketName: avatar #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Origami  #JWT负载中拿到开头